# Generated by Django 3.0.6 on 2020-11-09 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscs', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('addons', models.ManyToManyField(to='miscs.Addon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mill',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='miscs.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mill',
            name='mill_password',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mill',
            name='mill_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('payment_mode', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miscs.Bundle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnPurhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('payment_mode', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='miscs.Addon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Owner')),
            ],
        ),
    ]
