# Generated by Django 3.0.6 on 2020-11-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201109_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mill',
            name='is_active',
        ),
        migrations.AddField(
            model_name='mill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
