# Generated by Django 3.1.2 on 2020-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201025_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
