# Generated by Django 3.1.2 on 2020-10-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201025_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='code',
            field=models.CharField(default='abc', max_length=8),
            preserve_default=False,
        ),
    ]
