# Generated by Django 3.0.6 on 2020-11-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201109_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Owner'),
            preserve_default=False,
        ),
    ]
