# Generated by Django 3.0.6 on 2020-11-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201114_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='agreement_no',
        ),
    ]
