# Generated by Django 3.0.6 on 2020-11-14 10:15

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_firm_agreement_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='agreement_no',
            field=fernet_fields.fields.EncryptedField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
