# Generated by Django 3.0.6 on 2020-11-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_firm_agreement_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='agreement_no',
        ),
    ]
