# Generated by Django 3.0.6 on 2020-11-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_firm_agreement_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='conversion',
            field=models.FloatField(default=67.0),
        ),
    ]
