# Generated by Django 3.0.6 on 2020-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mill_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='ppq',
            field=models.FloatField(default=1400),
        ),
    ]
