# Generated by Django 3.0.6 on 2020-11-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0003_bundle_mills'),
        ('core', '0012_mill_ppq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonpurhase',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscs.Addon'),
        ),
        migrations.AlterField(
            model_name='addonpurhase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Owner'),
        ),
        migrations.AlterField(
            model_name='mill',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscs.City'),
        ),
        migrations.AlterField(
            model_name='mill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Owner'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscs.Bundle'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Owner'),
        ),
    ]
