# Generated by Django 3.0.6 on 2020-11-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201118_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('mobile', models.CharField(max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transporter')),
            ],
        ),
    ]
