# Generated by Django 3.0.6 on 2020-11-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transporter_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='cmr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmr_no', models.CharField(max_length=36)),
                ('cmr_date', models.DateField()),
                ('center', models.CharField(max_length=256)),
                ('rice', models.FloatField()),
                ('bora', models.FloatField()),
                ('lot_no', models.IntegerField()),
                ('commodity', models.CharField(max_length=512)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill')),
            ],
        ),
    ]
