# Generated by Django 3.0.6 on 2020-11-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201123_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmr_entry',
            name='entry_type',
            field=models.IntegerField(choices=[(1, 'FCI'), (2, 'NAN')], default=1),
        ),
    ]
