# Generated by Django 3.0.6 on 2020-11-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cmr_entry_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
