# Generated by Django 3.0.6 on 2020-12-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='order_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_id',
            field=models.CharField(max_length=255),
        ),
    ]
