# Generated by Django 3.0.6 on 2020-12-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
