# Generated by Django 3.0.6 on 2020-12-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_expense_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bill_type',
            field=models.CharField(default='New', max_length=512),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Truck')),
            ],
        ),
    ]
