# Generated by Django 3.0.6 on 2020-11-09 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingstockentry',
            name='include_trading',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.Stock')),
            ],
        ),
    ]
