# Generated by Django 3.0.6 on 2020-11-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20201109_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingstockentry',
            name='include_trading',
        ),
        migrations.AddField(
            model_name='incomingsource',
            name='include_trading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='materials.IncomingSource'),
        ),
    ]
