# Generated by Django 3.1.2 on 2020-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20201025_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingstockentry',
            name='date',
            field=models.DateField(),
        ),
    ]
