# Generated by Django 3.0.6 on 2020-11-10 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0004_auto_20201110_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trading',
            old_name='buying_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='trading',
            name='selling_price',
        ),
        migrations.AddField(
            model_name='trading',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trading',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
