# Generated by Django 3.0.6 on 2020-11-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20201026_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingstockentry',
            name='category',
        ),
    ]
