# Generated by Django 3.0.6 on 2020-11-10 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0005_auto_20201110_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
    ]
