# Generated by Django 3.0.6 on 2020-11-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20201110_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='source',
        ),
        migrations.AddField(
            model_name='incomingstockentry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='materials.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingstockentry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoingstockentrys', to='materials.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processingsideentry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='processingsideentrys', to='materials.Category'),
            preserve_default=False,
        ),
    ]
