# Generated by Django 3.0.6 on 2020-11-18 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20201118_1522'),
        ('materials', '0008_trading_mill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='mill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill'),
        ),
        migrations.AlterField(
            model_name='incomingsource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomingsource',
            name='mill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill'),
        ),
        migrations.AlterField(
            model_name='incomingstockentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outgoingsource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outgoingsource',
            name='mill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill'),
        ),
        migrations.AlterField(
            model_name='outgoingstockentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outgoingstockentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Stock'),
        ),
        migrations.AlterField(
            model_name='processingside',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processingside',
            name='mill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill'),
        ),
        migrations.AlterField(
            model_name='processingsideentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processingsideentry',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Stock'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trading',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Stock'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='mill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill'),
        ),
    ]
