# Generated by Django 3.0.6 on 2020-12-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_mobile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_do_request',
            field=models.BooleanField(default=False),
        ),
    ]
