# Generated by Django 3.0.6 on 2020-11-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscs', '0003_bundle_mills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='firms',
            field=models.IntegerField(default=3),
        ),
    ]
