# Generated by Django 3.0.6 on 2020-11-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontype',
            name='include_trading',
            field=models.BooleanField(default=False),
        ),
    ]
