# Generated by Django 3.0.6 on 2020-10-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingproductentry',
            old_name='source',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='outgoingproductentry',
            old_name='source',
            new_name='product_type',
        ),
        migrations.AddField(
            model_name='outgoingproductentry',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productiontype',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productiontypes', to='products.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productiontype',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
