# Generated by Django 3.1.2 on 2020-10-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201025_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproductentry',
            name='date',
            field=models.DateField(),
        ),
    ]
