# Generated by Django 3.0.6 on 2020-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_trading'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontype',
            name='is_mixture',
            field=models.BooleanField(default=False),
        ),
    ]
