# Generated by Django 3.0.6 on 2020-11-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
            preserve_default=False,
        ),
    ]
