# Generated by Django 3.0.6 on 2020-11-13 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mill_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_stock_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiontype',
            name='include_trading',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.AddField(
            model_name='incomingproductentry',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomingproductentry',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='incomingproductentrys', to='products.ProductionType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingproductentry',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingproductentry',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='outgoingproductentrys', to='products.ProductionType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstock',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='productstocks', to='products.ProductionType'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TradingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradingsources', to='products.ProductCategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('mill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Mill')),
            ],
        ),
        migrations.AddField(
            model_name='trading',
            name='source',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='products.TradingSource'),
            preserve_default=False,
        ),
    ]
