# Generated by Django 3.0.6 on 2020-11-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_tradingsource_mill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trading',
            name='source',
        ),
    ]
