# Generated by Django 3.0.6 on 2020-11-14 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_trading_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.TradingSource'),
            preserve_default=False,
        ),
    ]
