# Generated by Django 3.0.6 on 2020-11-18 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20201118_1522'),
        ('products', '0011_trading_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingproductentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outgoingproductentry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='mill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill'),
        ),
        migrations.AlterField(
            model_name='productiontype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productiontype',
            name='mill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mill'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trading',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trading',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Stock'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.TradingSource'),
        ),
        migrations.AlterField(
            model_name='tradingsource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
