# Generated by Django 3.0.6 on 2020-11-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rice'),
        ('products', '0012_auto_20201118_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='rice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, null=True, to='core.Rice'),
            preserve_default=False,
        ),
    ]
