# Generated by Django 3.0.6 on 2020-11-24 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rice'),
        ('products', '0013_productcategory_rice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='rice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Rice'),
        ),
    ]
