# Generated by Django 3.0.6 on 2020-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productiontype_is_biproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiontype',
            name='is_biproduct',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_biproduct',
            field=models.BooleanField(default=False),
        ),
    ]
