# Generated by Django 3.0.6 on 2020-12-28 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_auto_20201213_1949'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0017_auto_20201127_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('ppq', models.FloatField()),
                ('gst', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Customer')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.ProductionType')),
            ],
        ),
    ]
